### ISSUE TITLE
why *.cpp and not *.c

### ISSUE THREAD

**Issue by mgiaco** [mpaland/printf#1]
Is there any special reason why you use cpp?

many thanks

**Comment by mpaland** [comment]
@mgiaco Thanks for your interest!
It needs to be a C++ module in the moment cause it contains a templated `_ntoa()` function for number to ASCII conversion.
This is used/called with six different types (`int`, `long`, `long long` and in their unsigned form).
Basically a non templated standard `_ntoa()` implementation would be fine and perhaps better regarding compiled code size.

I leave this issue open and think about it.

**Comment by mgiaco** [comment]
Do you have any plans to Support C only?

**Comment by mpaland** [comment]
@mgiaco I created a no_ntoa_template branch which contains a pure non templated print.c version.
All tests are passing.
Please test this. If everything is fine, this will be merged into master.

**Comment by mgiaco** [comment]
hey sorry i was on holiday, many thanks i will test it

**Comment by mpaland** [comment]
No problem. The non-templated .c version is already merged and successfully tested.
If you encounter any problems, pls open a new issue.
