### ISSUE TITLE
redundant code `if (value != value)`

### ISSUE THREAD

**Issue by Umair-Anwar** [mpaland/printf#100]
In function `_ftoa` following if-condition is redundant `if (value != value)`. One similar redundant condition is present in function `_etoa` as well. Because _The same variable will always be equal._

**Comment by mjasperse** [comment]
Actually, you are incorrect. NAN does not equal itself, and that is what the check is for.

**Comment by Umair-Anwar** [comment]
Yeah, technically speaking you are correct but static code analysis tools like CodeSonar do not accept it. Anyways, thanks I did not see it was a double type.
