### ISSUE TITLE
this is incredible

### ISSUE THREAD

**Issue by rickyelopez** [mpaland/printf#132]
been banging my head against a HardFault due to newlib nano `snprintf` malloc call with FreeRTOS for days, this solved my issues instantly.
Beauty, thanks!

**Comment by eyalroz** [comment]
@rickyelopez : If by "this" you mean this library, note that it has been abandoned for over 2 years; I am maintaining a  fork with many bug fixes and some missing features: https://github.com/eyalroz/printf . Many thanks are due to mpaland, of course, for his work until 2019.

**Comment by rickyelopez** [comment]
oh hey thanks for pointing that out, I'll take a look!

**Comment by rickyelopez** [comment]
@eyalroz your fork takes up 4 more pages of ram than this one (on my chip at least) even with all the optional functionality disabled, and more importantly, crashes my display driver.

**Comment by mickjc750** [comment]
@rickyelopez 
If you want something lighter, you may like my prnf, it's not fully compatible with the standard printf though.
https://github.com/mickjc750/prnf

**Comment by eyalroz** [comment]
@rickyelopez : This is interesting. I would appreciate a bug report on my repository.

**Comment by rickyelopez** [comment]
> @rickyelopez If you want something lighter, you may like my prnf, it's not fully compatible with the standard printf though. https://github.com/mickjc750/prnf

I'll keep this in mind if I find myself having to shave off more space, thanks!



> @rickyelopez : This is interesting. I would appreciate a bug report on my repository.

I didn't really dig into it, but when I get a chance I can try it again and create an issue on your repo
