### ISSUE TITLE
WebAssembly

### ISSUE THREAD

**Issue by RobLoach** [mpaland/printf#134]
Just wanted to give you a thumbs up and say this project is awesome, and works well in WebAssembly where packing in some of the standard libs can bloat up WASM builds too much. Nice work!

Feel free to close this :wink:

**Comment by eyalroz** [comment]
@RobLoach : This repository is effectively abandoned, please see #128 .

**Comment by RobLoach** [comment]
Oh! This is great! Thanks for picking it up and rolling with it. 🚀
