### ISSUE TITLE
Scawy big unkown symbol UwU

### ISSUE THREAD

**Issue by MikuChan03** [mpaland/printf#14]
Hii~~

This time the types are all right and pwoper,
but nullptr isn't anything in C.

Can we have NULL pwease?

printf.c: In function 'printf':
printf.c:650:41: error: 'nullptr' undeclared (first use in this function)
   const int ret = _vsnprintf(_out_char, nullptr, (size_t)-1, format, va);

**Comment by mpaland** [comment]
> Can we have NULL pwease?

Sure!
Sorry, I'm just too long into C++ 😄

**Comment by donno2048** [comment]
NaNi?
