### ISSUE TITLE
File size not changing with disabled options 

### ISSUE THREAD

**Issue by Rockwell1799** [mpaland/printf#142]
Hello
I'm trying the printf project in Keil uvision ( STM32F4) and I'm having a problem decreasing the size of the file, even though I disabled the following option int the config file:

> #ifndef PRINTF_INCLUDE_CONFIG_H
#define PRINTF_INCLUDE_CONFIG_H

#define PRINTF_DISABLE_SUPPORT_EXPONENTIAL
#define PRINTF_DISABLE_SUPPORT_LONG_LONG
#define PRINTF_DISABLE_SUPPORT_PTRDIFF_T
#define PRINTF_DISABLE_SUPPORT_FLOAT

#endif

the file size is not changing at all 
Program Size: Code=11804 RO-data=548 RW-data=8 ZI-data=1640
![image](https://github.com/user-attachments/assets/987f9934-b920-47f2-ae11-cb4412805214)

  
Is there something I'm doing wrong?

**Comment by eyalroz** [comment]
You're asking a question on an un-maintained repository. The maintaining repository is here: https://github.com/eyalroz/printf
  see also issue #128 . Please consider closing this issue so that issue 128 remains the top one, to tell people where to go to try the newest version.

**Comment by Rockwell1799** [comment]
Thanks for the heads-up
