### ISSUE TITLE
Scawy big no functionality at all UwU

### ISSUE THREAD

**Issue by MikuChan03** [mpaland/printf#15]
Senpai,

your little kawaii pwintf impwementation is getting out of contwol.
Pwease have a look at this:

The pwintf function:
int printf(const char* format, ...)
{
&nbsp;&nbsp;va_list va;
&nbsp;&nbsp;va_start(va, format);
&nbsp;&nbsp;const int ret = _vsnprintf(_out_char, NULL, (size_t)-1, format, va);
&nbsp;&nbsp;va_end(va);
&nbsp;&nbsp;return ret;
}

The _vsnpwintf function:
static int _vsnprintf(out_fct_type out, char* buffer, const size_t maxlen, const char* format, va_list va)
{
&nbsp;&nbsp;unsigned int flags, width, precision, n;
&nbsp;&nbsp;size_t idx = 0U;

&nbsp;&nbsp;if (!buffer) {
&nbsp;&nbsp;&nbsp;&nbsp;// use null output function
&nbsp;&nbsp;&nbsp;&nbsp;out = _out_null;
&nbsp;&nbsp;}
...

Since we pass null fow the buffer, the output function is being set to _out_null,
which doesn't do anything. Pwintf has ceased functioning entirely.

Oh no!

**Comment by mpaland** [comment]
Sorry for inconvenience. That wasn't covered by any test case. Fixed now. Thanx!

**Comment by BRA1L0R** [comment]
What the fuck

**Comment by zapirka** [comment]
lmao  what the fuck

**Comment by TroyKomodo** [comment]
hello friends.

**Comment by ghost** [comment]
hello from reddit

**Comment by IcyDrae** [comment]
Did it get fixie wixied?

**Comment by larbikhounti** [comment]
😂

**Comment by regnaio** [comment]
(づ｡◕‿‿◕｡)づ
