### ISSUE TITLE
left aligned fields don't obey field field widths

### ISSUE THREAD

**Issue by johnruttenberg** [mpaland/printf#21]
Attaching a test to reproduce and a proposed patch to fix.

Try running the test with linux system printf and the result is:

```
Print with precison -2:
|    9| |9 | |    9|
|   10| |10| |   10|
Print with precision -12:
|    9| |9           | |    9|
|   10| |10          | |   10|
```

With your printf:

```
Print with precison -2:
|    9| |9| |    9|
|   10| |10| |   10|
Print with precision -12:
|    9| |9  | |    9|
|   10| |10 | |   10|
```

Note the missing padding.

See the attached proposed fix.

[printf.patch.txt](https://github.com/mpaland/printf/files/2298594/printf.patch.txt)
[test_printf.c.txt](https://github.com/mpaland/printf/files/2298596/test_printf.c.txt)

**Comment by mpaland** [comment]
Hello John,
thanks a lot for bringing this to attention, finding and providing a patch for this bug - which obviously is one.
Wondering why this wasn't covered by any test case yet.
Anyway, printf is still making progress... 😄 

I add this to the test case suite and fix the code. Unfortunately you havn't provided a PR, so you aren't visible in history, but credit is up to you. Thanx! 👍
