### ISSUE TITLE
Problems with zero precision

### ISSUE THREAD

**Issue by wm4** [mpaland/printf#26]
There are some problems with a precision of 0 (an annoying corner case).

The following crash:
- ``printf("% .0d", 0);`` (should output `` ``)
- ``printf("%+.0d", 0);`` (should output ``+``)

This is caused by decrementing a 0 ``len`` here: https://github.com/mpaland/printf/blob/master/printf.c#L185

``printf("%#.0x", 0);`` is apparently supposed to output an empty string, not ``0x``. The octal case is correct, though. It seems this was clarified in C11.

**Comment by mpaland** [comment]
Wow! This is really serious and leads to out of bounds buffer access!
Wondering that coverity didn't catch it.

**Comment by eyalroz** [comment]
The fix for this bug may have causes #109 .
