### ISSUE TITLE
Not standard on prefix + precision

### ISSUE THREAD

**Issue by NotSqrt** [mpaland/printf#31]
```c
printf("%#08x %#0.8x\n",0x614e,0x614e);

// currently:
0x00614e 0x00614e

// standard;
0x00614e 0x0000614e
```

(edited to show same bad behaviour, but with precision <= 9 instead of 10)

**Comment by mpaland** [comment]
The '0' flag is ignored with given precision and '%x', but anyway, the produced precision length is wrong.
Good catch!
