### ISSUE TITLE
need lib : stdio stdarg  in the include code

### ISSUE THREAD

**Issue by allenogz** [mpaland/printf#35]
Dear mpaland,
    hi, i am using ur printf in Arm process and RiscV lib,  to get the "printf " function with mimimum lib file
but i cannot get the stdio and stdarg in your code; so far as too many stdio and starg versions : MS VC6.0 /VC2.0 and so on.
     so i'd like to get stdio/stdarg from the your repo in github
    thank you!

**Comment by mpaland** [comment]
Hello @allenogz,
stdio.h is not necessary nor needed for this printf module and is not included anywhere.
stdarg.h is compiler dependent and can't be included in the project, sorry. Your compiler environment is always providing this file.
Using the brackets <stdarg.h> include option searches for stdarg.h in the compiler standard include path - and it should be always found there.
