### ISSUE TITLE
fctprintf & null termination

### ISSUE THREAD

**Issue by phillipjohnston** [mpaland/printf#39]
In using the `fctprintf` printf function, I notice that the NULL terminator is passed to the `out` function. In my experience, printing into a buffer should result in a NULL-terminator, but `printf` itself does not print the `NULL` byte.

My personal opinion is that `fctprintf` should match the `printf` behavior (updated in #19). Curious about your thoughts on the matter.

**Comment by mpaland** [comment]
@phillipjohnston, you are right! Thanks a lot for bringing this to attention.
`fctprintf()` should be like `fprintf()` which writes to streams. And terminating zeros should IMHO and as far as I know not be written to streams.
So this is confirmed to be a bug.
