### ISSUE TITLE
Digit missing from negative numbers in certain cases

### ISSUE THREAD

**Issue by vgrudenic** [mpaland/printf#40]
Hi, it seems that when the width specifier matches the number of digits in a negative number, one of the digits gets removed from the output, i.e.

```c
printf_ ("%2d", -123);   // --> prints -123 (ok)
printf_ ("%3d", -123);   // --> printf -23 ('1' is missing)
printf_ ("%4d", -123);   // --> printf -123 (ok)
```

The same issue happens with `("%1d", -1)` or `("%2d", -12)`, for example.

The point where this happens is [this line](https://github.com/mpaland/printf/blob/c013a0e8d6bb57247074c748a05bbe7f43bdec6f/printf.c#L212):

```c
// when len == width, removes the last digit in the inverted output, 
// before writing the `-` character
if (len && (len == width) && (negative || (flags & FLAGS_PLUS) || (flags & FLAGS_SPACE))) {
    len--;
}
```

**Comment by mpaland** [comment]
Thank A LOT for the PR and finding this bug!
Merged.

**Comment by vgrudenic** [comment]
No problem, thanks for this incredibly useful library!
