### ISSUE TITLE
Please add Hatchling Platform to your Using printf section.

### ISSUE THREAD

**Issue by adrian3git** [mpaland/printf#44]
Hatchling Platform is a small C++ run-time intended to be developed against on the desktop before cross compiling to an embedded target.

It is using your printf and I would like to be mentioned in your "Using printf" section.

The project page is at:  https://github.com/adrian3git/HatchlingPlatform

Thank you, and let me know if you have any questions.

**Comment by mpaland** [comment]
Appreciate that! Will be added shortly.

**Comment by mpaland** [comment]
Closed by https://github.com/mpaland/printf/commit/b20ddfb40f7a2f8ab312078698211186d80d6e1a
