### ISSUE TITLE
snprintf() and vsnprintf() return value comment

### ISSUE THREAD

**Issue by vgrudenic** [mpaland/printf#45]
Hi, just a tiny remark: the [comment for `snprintf`/`vsnprintf`](https://github.com/mpaland/printf/blob/master/printf.h#L75) seems to be incorrect:

> (returns) The number of characters that are WRITTEN into the buffer, not counting the terminating null character. If the formatted string is truncated the buffer size (count) is returned

The description in the [readme file](https://github.com/mpaland/printf#return-value) is ok:

> Anyway, if the output was truncated due to this limit, the return value is the number of characters that _could_ have been written. Notice that a value equal or larger than `count` indicates a truncation.

I made a quick update so I'll place a PR (I didn't find the `-1` being returned from anywhere in case of errors, so I didn't mention it explicitly).

**Comment by mpaland** [comment]
Thanks a lot for the PR, Vedran.
