### ISSUE TITLE
Not working in freertos, are you sure it's threadsafe?

### ISSUE THREAD

**Issue by mttbx** [mpaland/printf#64]
I use this function in freertos. It makes freertos stucked in one task(thread, can't switch to other tasks). And when I call osDelay, it returns osErrorISR.

**Comment by ledvinap** [comment]
@mttbx : You should also check actual output function, it may be not thread safe/callable from ISR context ...

**Comment by mttbx** [comment]
Thank you! I closed my issue because I found I may think it the wrong way.
