### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [mpaland/printf#70]
Hi,

I am using this on RISC V, RV32I and doing this:

`    uint32_t dest1 = 0xDEADBABE;
    uint32_t dest2 = 0xDEADBEEF;
printf("Hello, World! dest1 = 0x%08X, dest2 = 0x%08X", dest1, dest2);`

likewise
`printf("Hello, World! dest1 = 0x%08X, dest2 = 0x%08X", 0xDEADBABE, 0xDEADBEEF);`

prints "Hello, World! dest1 = 0x%, dest2 = 0x%"

Also:

`printf("Timebase = %d s %d ns", s3, ns3);`

prints "Timebase = % s % ns" ....

**Comment by mpaland** [comment]
Could you figure out the problem?

**Comment by ghost** [comment]
Yes sorry I had implemented all shifts except for SLL, sorryyyyyyyy!
