### ISSUE TITLE
puts must append newline 

### ISSUE THREAD

**Issue by aautotte** [mpaland/printf#91]
> int puts ( const char * str );
> Write string to stdout
> Writes the C string pointed by str to the standard output (stdout) and appends a newline character ('\n').
> 
> The function begins copying from the address specified (str) until it reaches the terminating null character ('\0'). This terminating null-character is not copied to the stream.
> 
> Notice that puts not only differs from fputs in that it uses stdout as destination, but it also appends a newline character at the end automatically (which fputs does not).

https://www.cplusplus.com/reference/cstdio/puts/

**Comment by vgrudenic** [comment]
I wasn't able to find the `puts` function in this repository, can you clarify your issue a bit better?

**Comment by aautotte** [comment]
Sorry It was in a fork
